"""Remove user_id from reports

Revision ID: 708b0e0a309c
Revises: 1faba87319f4
Create Date: 2025-09-29 23:51:09.613362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '708b0e0a309c'
down_revision: Union[str, Sequence[str], None] = '1faba87319f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bins', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bins', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('bins', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_bins_latitude'), table_name='bins')
    op.drop_index(op.f('ix_bins_longitude'), table_name='bins')
    op.drop_index(op.f('ix_bins_location'), table_name='bins')
    op.create_index(op.f('ix_bins_location'), 'bins', ['location'], unique=True)
    op.add_column('reports', sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('reports', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_reports_bin_id'), table_name='reports')
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.create_index(op.f('ix_reports_bin_id'), 'reports', ['bin_id'], unique=False)
    op.alter_column('reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('reports', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('reports', 'cleared_at')
    op.drop_index(op.f('ix_bins_location'), table_name='bins')
    op.create_index(op.f('ix_bins_location'), 'bins', ['location'], unique=False)
    op.create_index(op.f('ix_bins_longitude'), 'bins', ['longitude'], unique=False)
    op.create_index(op.f('ix_bins_latitude'), 'bins', ['latitude'], unique=False)
    op.alter_column('bins', 'longitude',
               existing_type=sa.String(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('bins', 'latitude',
               existing_type=sa.String(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('bins', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
